title : Deploy a machine learning model on Kubernetes
author :
  name : Fraida Fund
  email : ffund@nyu.edu
  github : ffund
  feedburner : nil

theme: jekyll-theme-cayman
exclude: 
 - "*"
include:
 - "README.md"

